drop table if exists ss_actions;
create table ss_actions (
  id bigint generated by default as identity (start with 1),
  jiraKey varchar(255),
  institutionId varchar(255),
  userId varchar(1024),
  userName varchar(1024),
  actionType varchar(255),
  actionStatus varchar(255),
  body varchar(4096),
  idp varchar(255),
  sp varchar(255),
  requestDate timestamp default CURRENT_TIMESTAMP,
  primary key (id)
);

INSERT INTO ss_actions (id, jiraKey, institutionId, userId, userName, actionType, actionStatus, body, idp, sp, requestDate) VALUES (1, 'TEST-100', 'SURFNET', 'urn:collab:person:surfnet.nl:jdoe', 'John Doe', 'LINKREQUEST', 'OPEN', 'Test data link request', 'http://mock-idp', 'http://mock-sp', '2012-10-18 13:42:11');
INSERT INTO ss_actions (id, jiraKey, institutionId, userId, userName, actionType, actionStatus, body, idp, sp, requestDate) VALUES (2, 'TEST-101', 'SURFNET', 'urn:collab:person:surfnet.nl:jdoe', 'John Doe', 'UNLINKREQUEST', 'OPEN', 'Test data unlink request', 'http://mock-idp', 'http://mock-sp', '2012-10-18 13:42:11');
INSERT INTO ss_actions (id, jiraKey, institutionId, userId, userName, actionType, actionStatus, body, idp, sp, requestDate) VALUES (3, 'TEST-102', 'SURFNET', 'urn:collab:person:surfnet.nl:jdoe', 'John Doe', 'QUESTION', 'CLOSED', 'Test data question', 'http://mock-idp', 'http://mock-sp', '2012-10-18 13:42:11');