DROP TABLE IF EXISTS screenshot;
DROP TABLE IF EXISTS multilingual_string;
DROP TABLE IF EXISTS localized_string;
DROP TABLE IF EXISTS field_string;
DROP TABLE IF EXISTS field_image;
DROP TABLE IF EXISTS facet_value_compound_service_provider;
DROP TABLE IF EXISTS facet_value;
DROP TABLE IF EXISTS facet;
DROP TABLE IF EXISTS compound_service_provider;

CREATE TABLE compound_service_provider (id                         BIGINT GENERATED BY DEFAULT AS IDENTITY (
START WITH 1 ),                         hide_in_protected_showroom BIT, hide_in_public_showroom BIT, lmng_id VARCHAR(255), service_provider_entity_id VARCHAR(255), PRIMARY KEY (id), UNIQUE (service_provider_entity_id));

CREATE TABLE facet (id                     BIGINT GENERATED BY DEFAULT AS IDENTITY (
START WITH 1 ),     multilingual_string_id BIGINT NOT NULL, facet_parent_id BIGINT, PRIMARY KEY (id));

CREATE TABLE facet_value (id       BIGINT GENERATED BY DEFAULT AS IDENTITY (
START WITH 1 ),           facet_id BIGINT NOT NULL, multilingual_string_id BIGINT NOT NULL, PRIMARY KEY (id));

CREATE TABLE facet_value_compound_service_provider (compound_service_provider_id BIGINT NOT NULL, facet_value_id BIGINT NOT NULL, PRIMARY KEY (compound_service_provider_id, facet_value_id));

CREATE TABLE field_image (id        BIGINT GENERATED BY DEFAULT AS IDENTITY (
START WITH 1 ),           field_key INTEGER, field_source INTEGER, field_image LONGVARBINARY, compound_service_provider_id BIGINT NOT NULL, PRIMARY KEY (id));

CREATE TABLE field_string (id        BIGINT GENERATED BY DEFAULT AS IDENTITY (
START WITH 1 ),            field_key INTEGER, field_source INTEGER, field_value VARCHAR(65535), compound_service_provider_id BIGINT NOT NULL, PRIMARY KEY (id));

CREATE TABLE localized_string (id     BIGINT GENERATED BY DEFAULT AS IDENTITY (
START WITH 1 ),                locale VARCHAR(255), value VARCHAR(255), multilingual_string_id BIGINT NOT NULL, PRIMARY KEY (id));

CREATE TABLE multilingual_string (id BIGINT GENERATED BY DEFAULT AS IDENTITY (
START WITH 1 ), PRIMARY KEY (id));

CREATE TABLE screenshot (id          BIGINT GENERATED BY DEFAULT AS IDENTITY (
START WITH 1 ),          field_image LONGVARBINARY, compound_service_provider_id BIGINT NOT NULL, PRIMARY KEY (id));

ALTER TABLE facet ADD CONSTRAINT FK5CAF5B77DCB0965 FOREIGN KEY (multilingual_string_id) REFERENCES multilingual_string;
ALTER TABLE facet ADD CONSTRAINT FK5CAF5B7FD0228F7 FOREIGN KEY (facet_parent_id) REFERENCES facet;
ALTER TABLE facet_value ADD CONSTRAINT FKD65C84E9D82B8D52 FOREIGN KEY (facet_id) REFERENCES facet;
ALTER TABLE facet_value ADD CONSTRAINT FKD65C84E97DCB0965 FOREIGN KEY (multilingual_string_id) REFERENCES multilingual_string;
ALTER TABLE facet_value_compound_service_provider ADD CONSTRAINT FK76FE8C79D151AC27 FOREIGN KEY (compound_service_provider_id) REFERENCES compound_service_provider;
ALTER TABLE facet_value_compound_service_provider ADD CONSTRAINT FK76FE8C792ED80E33 FOREIGN KEY (facet_value_id) REFERENCES facet_value;
ALTER TABLE field_image ADD CONSTRAINT FK294389D6D151AC27 FOREIGN KEY (compound_service_provider_id) REFERENCES compound_service_provider;
ALTER TABLE field_string ADD CONSTRAINT FK10A88EF6D151AC27 FOREIGN KEY (compound_service_provider_id) REFERENCES compound_service_provider;
ALTER TABLE localized_string ADD CONSTRAINT FK1310C9557DCB0965 FOREIGN KEY (multilingual_string_id) REFERENCES multilingual_string;
ALTER TABLE screenshot ADD CONSTRAINT FKE72D8566D151AC27 FOREIGN KEY (compound_service_provider_id) REFERENCES compound_service_provider;
